version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/polyvote"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/polyvote/functions"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
